#Server
server:
  port: 8081

#Log
logging:
  file:
    path: logs
  level:
    com.login.test: DEBUG

#Spring
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    converters:
      preferred-json-mapper: gson
  jackson:
    serialization:
      write-dates-as-timestamps: false
  #hikari:
  datasource:
    url: jdbc:postgresql://localhost:5432/bulletin_board?zeroDateTimeBehavior=convertToNull 
    #jdbc-url: jdbc:postgresql://winect_md_db/bmtsysmd?zeroDateTimeBehavior=convertToNull
    driver-class-name: org.postgresql.Driver # net.sf.log4jdbc.sql.jdbcapi.DriverSpy #
    username: postgres #postgres 
    password: postgres  #postgres
    #connection-test-query: select 1
    #maximum-pool-size: 50

  #JPA Configuration
  jpa:
    generate-ddl: true
    open-in-view: false
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties: 
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  #Security
  security:
    user:      name: login_admin
      password: poiu098)(*

#JWT
jwt:
  secret: JWTSuperSecretKey
